### PR TITLE
Refactor/tracer

### LINKED ISSUE #21: Tracer Refactor
We need a cleanup of the tracer implementation, with separate methods and calls for each different event that the tracer can fire on.

### PR DESCRIPTION
**Pull request by bengsparks**
Please check thoroughly! Closes #21

### CODE REVIEW

**Comment by RecurvedBow** [comment]
Some small comments: Due to the refactor, the line number of local variable declarations has increased by 1. For example, if variable a is declared at line 10, the trace data stores the value of 11 for variable name a instead.

**Comment by RecurvedBow** [comment]
Note: Build dataframe has been changed to update trace data instead. Instead of using a dictionary, rows are appended instead. Reason is probably  that due to the different value types in the dictionary, it evaluates all as of type object, causing the tracer test to fail. 

The reason why I changed the defintion of trace data update is that currently, types of columns can not be enforced on creation. Instead, the column type has to be set again after every update. In my opinion, this is less efficient than adding the rows directly. A disadvantage of this change is that the order of the row values is now important compared to using a dictionary. However, the unit tests should detect if a added row contains the values in the wrong order. Due to these reasons, I changed it.

**Comment by bengsparks** [comment]
> The reason why I changed the defintion of trace data update is that currently, types of columns can not be enforced on creation.
The `astype` method on DataFrames can be used to enforce types upon initialisation. I will implement this and ping you again when it is done.

**Comment by bengsparks** [comment]
@RecurvedBow If you think this is good enough then it's time to hit that merge button :point_right::sunglasses::point_right:

**Comment by RecurvedBow** [comment]
Yeah, LGTM!

**Pull request merged**
